import './globals.css'
import Link from 'next/link'
import styles from '@/app/page.module.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" />
      </head>
      <body>
        <nav className={styles.nav} class="">
          <ul class="navbar-nav">
            <li>Alpha Bank</li>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/accounts/add">Add Account</Link>
            </li>
            <li>
              <Link href="/accounts/transaction">Add Transaction</Link>
            </li>
          </ul>
        </nav>
        <hr />
        {children}
      </body>
    </html >
  )
}
